spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yb123456
    url: jdbc:mysql://127.0.0.1/test?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
