spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yb123456
    url: jdbc:mysql://47.98.192.65/test?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
